// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: render_server.proto
#ifndef GRPC_render_5fserver_2eproto__INCLUDED
#define GRPC_render_5fserver_2eproto__INCLUDED

#include "render_server.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace render_server {

class RenderWorker final {
 public:
  static constexpr char const* service_full_name() {
    return "render_server.RenderWorker";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::render_server::RenderJobResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderJobResponse>> AsyncRenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderJobResponse>>(AsyncRenderJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderJobResponse>> PrepareAsyncRenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderJobResponse>>(PrepareAsyncRenderJobRaw(context, request, cq));
    }
    virtual ::grpc::Status RenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::render_server::RenderStatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderStatusResponse>> AsyncRenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderStatusResponse>>(AsyncRenderStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderStatusResponse>> PrepareAsyncRenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderStatusResponse>>(PrepareAsyncRenderStatusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest* request, ::render_server::RenderJobResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest* request, ::render_server::RenderJobResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest* request, ::render_server::RenderStatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest* request, ::render_server::RenderStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderJobResponse>* AsyncRenderJobRaw(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderJobResponse>* PrepareAsyncRenderJobRaw(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderStatusResponse>* AsyncRenderStatusRaw(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::render_server::RenderStatusResponse>* PrepareAsyncRenderStatusRaw(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::render_server::RenderJobResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::render_server::RenderJobResponse>> AsyncRenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::render_server::RenderJobResponse>>(AsyncRenderJobRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::render_server::RenderJobResponse>> PrepareAsyncRenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::render_server::RenderJobResponse>>(PrepareAsyncRenderJobRaw(context, request, cq));
    }
    ::grpc::Status RenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::render_server::RenderStatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::render_server::RenderStatusResponse>> AsyncRenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::render_server::RenderStatusResponse>>(AsyncRenderStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::render_server::RenderStatusResponse>> PrepareAsyncRenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::render_server::RenderStatusResponse>>(PrepareAsyncRenderStatusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest* request, ::render_server::RenderJobResponse* response, std::function<void(::grpc::Status)>) override;
      void RenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest* request, ::render_server::RenderJobResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest* request, ::render_server::RenderStatusResponse* response, std::function<void(::grpc::Status)>) override;
      void RenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest* request, ::render_server::RenderStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::render_server::RenderJobResponse>* AsyncRenderJobRaw(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::render_server::RenderJobResponse>* PrepareAsyncRenderJobRaw(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::render_server::RenderStatusResponse>* AsyncRenderStatusRaw(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::render_server::RenderStatusResponse>* PrepareAsyncRenderStatusRaw(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RenderJob_;
    const ::grpc::internal::RpcMethod rpcmethod_RenderStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RenderJob(::grpc::ServerContext* context, const ::render_server::RenderJobRequest* request, ::render_server::RenderJobResponse* response);
    virtual ::grpc::Status RenderStatus(::grpc::ServerContext* context, const ::render_server::RenderStatusRequest* request, ::render_server::RenderStatusResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RenderJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RenderJob() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RenderJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RenderJob(::grpc::ServerContext* /*context*/, const ::render_server::RenderJobRequest* /*request*/, ::render_server::RenderJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRenderJob(::grpc::ServerContext* context, ::render_server::RenderJobRequest* request, ::grpc::ServerAsyncResponseWriter< ::render_server::RenderJobResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RenderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RenderStatus() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RenderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RenderStatus(::grpc::ServerContext* /*context*/, const ::render_server::RenderStatusRequest* /*request*/, ::render_server::RenderStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRenderStatus(::grpc::ServerContext* context, ::render_server::RenderStatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::render_server::RenderStatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RenderJob<WithAsyncMethod_RenderStatus<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RenderJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RenderJob() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::render_server::RenderJobRequest, ::render_server::RenderJobResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::render_server::RenderJobRequest* request, ::render_server::RenderJobResponse* response) { return this->RenderJob(context, request, response); }));}
    void SetMessageAllocatorFor_RenderJob(
        ::grpc::MessageAllocator< ::render_server::RenderJobRequest, ::render_server::RenderJobResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::render_server::RenderJobRequest, ::render_server::RenderJobResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RenderJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RenderJob(::grpc::ServerContext* /*context*/, const ::render_server::RenderJobRequest* /*request*/, ::render_server::RenderJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RenderJob(
      ::grpc::CallbackServerContext* /*context*/, const ::render_server::RenderJobRequest* /*request*/, ::render_server::RenderJobResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RenderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RenderStatus() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::render_server::RenderStatusRequest, ::render_server::RenderStatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::render_server::RenderStatusRequest* request, ::render_server::RenderStatusResponse* response) { return this->RenderStatus(context, request, response); }));}
    void SetMessageAllocatorFor_RenderStatus(
        ::grpc::MessageAllocator< ::render_server::RenderStatusRequest, ::render_server::RenderStatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::render_server::RenderStatusRequest, ::render_server::RenderStatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RenderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RenderStatus(::grpc::ServerContext* /*context*/, const ::render_server::RenderStatusRequest* /*request*/, ::render_server::RenderStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RenderStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::render_server::RenderStatusRequest* /*request*/, ::render_server::RenderStatusResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RenderJob<WithCallbackMethod_RenderStatus<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RenderJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RenderJob() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RenderJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RenderJob(::grpc::ServerContext* /*context*/, const ::render_server::RenderJobRequest* /*request*/, ::render_server::RenderJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RenderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RenderStatus() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RenderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RenderStatus(::grpc::ServerContext* /*context*/, const ::render_server::RenderStatusRequest* /*request*/, ::render_server::RenderStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RenderJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RenderJob() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RenderJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RenderJob(::grpc::ServerContext* /*context*/, const ::render_server::RenderJobRequest* /*request*/, ::render_server::RenderJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRenderJob(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RenderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RenderStatus() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RenderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RenderStatus(::grpc::ServerContext* /*context*/, const ::render_server::RenderStatusRequest* /*request*/, ::render_server::RenderStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRenderStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RenderJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RenderJob() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RenderJob(context, request, response); }));
    }
    ~WithRawCallbackMethod_RenderJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RenderJob(::grpc::ServerContext* /*context*/, const ::render_server::RenderJobRequest* /*request*/, ::render_server::RenderJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RenderJob(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RenderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RenderStatus() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RenderStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_RenderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RenderStatus(::grpc::ServerContext* /*context*/, const ::render_server::RenderStatusRequest* /*request*/, ::render_server::RenderStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RenderStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RenderJob : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RenderJob() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::render_server::RenderJobRequest, ::render_server::RenderJobResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::render_server::RenderJobRequest, ::render_server::RenderJobResponse>* streamer) {
                       return this->StreamedRenderJob(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RenderJob() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RenderJob(::grpc::ServerContext* /*context*/, const ::render_server::RenderJobRequest* /*request*/, ::render_server::RenderJobResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRenderJob(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::render_server::RenderJobRequest,::render_server::RenderJobResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RenderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RenderStatus() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::render_server::RenderStatusRequest, ::render_server::RenderStatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::render_server::RenderStatusRequest, ::render_server::RenderStatusResponse>* streamer) {
                       return this->StreamedRenderStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RenderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RenderStatus(::grpc::ServerContext* /*context*/, const ::render_server::RenderStatusRequest* /*request*/, ::render_server::RenderStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRenderStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::render_server::RenderStatusRequest,::render_server::RenderStatusResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RenderJob<WithStreamedUnaryMethod_RenderStatus<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RenderJob<WithStreamedUnaryMethod_RenderStatus<Service > > StreamedService;
};

}  // namespace render_server


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_render_5fserver_2eproto__INCLUDED
