// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: render_server.proto

#include "render_server.pb.h"
#include "render_server.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace render_server {

static const char* RenderWorker_method_names[] = {
  "/render_server.RenderWorker/RenderJob",
  "/render_server.RenderWorker/RenderStatus",
};

std::unique_ptr< RenderWorker::Stub> RenderWorker::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RenderWorker::Stub> stub(new RenderWorker::Stub(channel, options));
  return stub;
}

RenderWorker::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RenderJob_(RenderWorker_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RenderStatus_(RenderWorker_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RenderWorker::Stub::RenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::render_server::RenderJobResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::render_server::RenderJobRequest, ::render_server::RenderJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RenderJob_, context, request, response);
}

void RenderWorker::Stub::async::RenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest* request, ::render_server::RenderJobResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::render_server::RenderJobRequest, ::render_server::RenderJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RenderJob_, context, request, response, std::move(f));
}

void RenderWorker::Stub::async::RenderJob(::grpc::ClientContext* context, const ::render_server::RenderJobRequest* request, ::render_server::RenderJobResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RenderJob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::render_server::RenderJobResponse>* RenderWorker::Stub::PrepareAsyncRenderJobRaw(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::render_server::RenderJobResponse, ::render_server::RenderJobRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RenderJob_, context, request);
}

::grpc::ClientAsyncResponseReader< ::render_server::RenderJobResponse>* RenderWorker::Stub::AsyncRenderJobRaw(::grpc::ClientContext* context, const ::render_server::RenderJobRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRenderJobRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RenderWorker::Stub::RenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::render_server::RenderStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::render_server::RenderStatusRequest, ::render_server::RenderStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RenderStatus_, context, request, response);
}

void RenderWorker::Stub::async::RenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest* request, ::render_server::RenderStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::render_server::RenderStatusRequest, ::render_server::RenderStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RenderStatus_, context, request, response, std::move(f));
}

void RenderWorker::Stub::async::RenderStatus(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest* request, ::render_server::RenderStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RenderStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::render_server::RenderStatusResponse>* RenderWorker::Stub::PrepareAsyncRenderStatusRaw(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::render_server::RenderStatusResponse, ::render_server::RenderStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RenderStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::render_server::RenderStatusResponse>* RenderWorker::Stub::AsyncRenderStatusRaw(::grpc::ClientContext* context, const ::render_server::RenderStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRenderStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

RenderWorker::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RenderWorker_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RenderWorker::Service, ::render_server::RenderJobRequest, ::render_server::RenderJobResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RenderWorker::Service* service,
             ::grpc::ServerContext* ctx,
             const ::render_server::RenderJobRequest* req,
             ::render_server::RenderJobResponse* resp) {
               return service->RenderJob(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RenderWorker_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RenderWorker::Service, ::render_server::RenderStatusRequest, ::render_server::RenderStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RenderWorker::Service* service,
             ::grpc::ServerContext* ctx,
             const ::render_server::RenderStatusRequest* req,
             ::render_server::RenderStatusResponse* resp) {
               return service->RenderStatus(ctx, req, resp);
             }, this)));
}

RenderWorker::Service::~Service() {
}

::grpc::Status RenderWorker::Service::RenderJob(::grpc::ServerContext* context, const ::render_server::RenderJobRequest* request, ::render_server::RenderJobResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RenderWorker::Service::RenderStatus(::grpc::ServerContext* context, const ::render_server::RenderStatusRequest* request, ::render_server::RenderStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace render_server
#include <grpcpp/ports_undef.inc>

