// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scheduler_server.proto
// Protobuf C++ Version: 6.31.1

#include "scheduler_server.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace scheduler_server {

inline constexpr WorkerConncetion::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        worker_ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR WorkerConncetion::WorkerConncetion(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WorkerConncetion_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WorkerConncetionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WorkerConncetionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WorkerConncetionDefaultTypeInternal() {}
  union {
    WorkerConncetion _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WorkerConncetionDefaultTypeInternal _WorkerConncetion_default_instance_;
}  // namespace scheduler_server
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_scheduler_5fserver_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_scheduler_5fserver_2eproto = nullptr;
const ::uint32_t
    TableStruct_scheduler_5fserver_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::scheduler_server::WorkerConncetion, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::scheduler_server::WorkerConncetion, _impl_.worker_ip_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::scheduler_server::WorkerConncetion)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::scheduler_server::_WorkerConncetion_default_instance_._instance,
};
const char descriptor_table_protodef_scheduler_5fserver_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026scheduler_server.proto\022\020scheduler_serv"
    "er\032\033google/protobuf/empty.proto\"%\n\020Worke"
    "rConncetion\022\021\n\tworker_ip\030\001 \001(\t2e\n\020Worker"
    "Connection\022Q\n\023EstablishConnection\022\".sche"
    "duler_server.WorkerConncetion\032\026.google.p"
    "rotobuf.Emptyb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_scheduler_5fserver_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_scheduler_5fserver_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_scheduler_5fserver_2eproto = {
    false,
    false,
    221,
    descriptor_table_protodef_scheduler_5fserver_2eproto,
    "scheduler_server.proto",
    &descriptor_table_scheduler_5fserver_2eproto_once,
    descriptor_table_scheduler_5fserver_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_scheduler_5fserver_2eproto::offsets,
    file_level_enum_descriptors_scheduler_5fserver_2eproto,
    file_level_service_descriptors_scheduler_5fserver_2eproto,
};
namespace scheduler_server {
// ===================================================================

class WorkerConncetion::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WorkerConncetion>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WorkerConncetion, _impl_._has_bits_);
};

WorkerConncetion::WorkerConncetion(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WorkerConncetion_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:scheduler_server.WorkerConncetion)
}
PROTOBUF_NDEBUG_INLINE WorkerConncetion::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::scheduler_server::WorkerConncetion& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        worker_ip_(arena, from.worker_ip_) {}

WorkerConncetion::WorkerConncetion(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WorkerConncetion& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WorkerConncetion_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WorkerConncetion* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:scheduler_server.WorkerConncetion)
}
PROTOBUF_NDEBUG_INLINE WorkerConncetion::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        worker_ip_(arena) {}

inline void WorkerConncetion::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
WorkerConncetion::~WorkerConncetion() {
  // @@protoc_insertion_point(destructor:scheduler_server.WorkerConncetion)
  SharedDtor(*this);
}
inline void WorkerConncetion::SharedDtor(MessageLite& self) {
  WorkerConncetion& this_ = static_cast<WorkerConncetion&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.worker_ip_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WorkerConncetion::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WorkerConncetion(arena);
}
constexpr auto WorkerConncetion::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WorkerConncetion),
                                            alignof(WorkerConncetion));
}
constexpr auto WorkerConncetion::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WorkerConncetion_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WorkerConncetion::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WorkerConncetion>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WorkerConncetion::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WorkerConncetion>(), &WorkerConncetion::ByteSizeLong,
              &WorkerConncetion::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WorkerConncetion, _impl_._cached_size_),
          false,
      },
      &WorkerConncetion::kDescriptorMethods,
      &descriptor_table_scheduler_5fserver_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WorkerConncetion_class_data_ =
        WorkerConncetion::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WorkerConncetion::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WorkerConncetion_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WorkerConncetion_class_data_.tc_table);
  return WorkerConncetion_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 51, 2>
WorkerConncetion::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WorkerConncetion, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WorkerConncetion_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::scheduler_server::WorkerConncetion>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string worker_ip = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(WorkerConncetion, _impl_.worker_ip_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string worker_ip = 1;
    {PROTOBUF_FIELD_OFFSET(WorkerConncetion, _impl_.worker_ip_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\41\11\0\0\0\0\0\0"
    "scheduler_server.WorkerConncetion"
    "worker_ip"
  }},
};
PROTOBUF_NOINLINE void WorkerConncetion::Clear() {
// @@protoc_insertion_point(message_clear_start:scheduler_server.WorkerConncetion)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.worker_ip_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WorkerConncetion::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WorkerConncetion& this_ = static_cast<const WorkerConncetion&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WorkerConncetion::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WorkerConncetion& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:scheduler_server.WorkerConncetion)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string worker_ip = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_worker_ip().empty()) {
      const ::std::string& _s = this_._internal_worker_ip();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "scheduler_server.WorkerConncetion.worker_ip");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:scheduler_server.WorkerConncetion)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WorkerConncetion::ByteSizeLong(const MessageLite& base) {
  const WorkerConncetion& this_ = static_cast<const WorkerConncetion&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WorkerConncetion::ByteSizeLong() const {
  const WorkerConncetion& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:scheduler_server.WorkerConncetion)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string worker_ip = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_worker_ip().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_worker_ip());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WorkerConncetion::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WorkerConncetion*>(&to_msg);
  auto& from = static_cast<const WorkerConncetion&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:scheduler_server.WorkerConncetion)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_worker_ip().empty()) {
      _this->_internal_set_worker_ip(from._internal_worker_ip());
    } else {
      if (_this->_impl_.worker_ip_.IsDefault()) {
        _this->_internal_set_worker_ip("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WorkerConncetion::CopyFrom(const WorkerConncetion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:scheduler_server.WorkerConncetion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WorkerConncetion::InternalSwap(WorkerConncetion* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.worker_ip_, &other->_impl_.worker_ip_, arena);
}

::google::protobuf::Metadata WorkerConncetion::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace scheduler_server
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_scheduler_5fserver_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
