// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: scheduler_server.proto

#include "scheduler_server.pb.h"
#include "scheduler_server.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace scheduler_server {

static const char* WorkerConnection_method_names[] = {
  "/scheduler_server.WorkerConnection/EstablishConnection",
};

std::unique_ptr< WorkerConnection::Stub> WorkerConnection::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WorkerConnection::Stub> stub(new WorkerConnection::Stub(channel, options));
  return stub;
}

WorkerConnection::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_EstablishConnection_(WorkerConnection_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WorkerConnection::Stub::EstablishConnection(::grpc::ClientContext* context, const ::scheduler_server::WorkerConncetion& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::scheduler_server::WorkerConncetion, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EstablishConnection_, context, request, response);
}

void WorkerConnection::Stub::async::EstablishConnection(::grpc::ClientContext* context, const ::scheduler_server::WorkerConncetion* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::scheduler_server::WorkerConncetion, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EstablishConnection_, context, request, response, std::move(f));
}

void WorkerConnection::Stub::async::EstablishConnection(::grpc::ClientContext* context, const ::scheduler_server::WorkerConncetion* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EstablishConnection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* WorkerConnection::Stub::PrepareAsyncEstablishConnectionRaw(::grpc::ClientContext* context, const ::scheduler_server::WorkerConncetion& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::scheduler_server::WorkerConncetion, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EstablishConnection_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* WorkerConnection::Stub::AsyncEstablishConnectionRaw(::grpc::ClientContext* context, const ::scheduler_server::WorkerConncetion& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEstablishConnectionRaw(context, request, cq);
  result->StartCall();
  return result;
}

WorkerConnection::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerConnection_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerConnection::Service, ::scheduler_server::WorkerConncetion, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerConnection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::scheduler_server::WorkerConncetion* req,
             ::google::protobuf::Empty* resp) {
               return service->EstablishConnection(ctx, req, resp);
             }, this)));
}

WorkerConnection::Service::~Service() {
}

::grpc::Status WorkerConnection::Service::EstablishConnection(::grpc::ServerContext* context, const ::scheduler_server::WorkerConncetion* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace scheduler_server
#include <grpcpp/ports_undef.inc>

