// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: render_server.proto
// Protobuf C++ Version: 6.33.4

#ifndef render_5fserver_2eproto_2epb_2eh
#define render_5fserver_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_render_5fserver_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_render_5fserver_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_render_5fserver_2eproto;
}  // extern "C"
namespace render_server {
enum Status : int;
extern const uint32_t Status_internal_data_[];
class RenderJobRequest;
struct RenderJobRequestDefaultTypeInternal;
extern RenderJobRequestDefaultTypeInternal _RenderJobRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RenderJobRequest_class_data_;
class RenderJobResponse;
struct RenderJobResponseDefaultTypeInternal;
extern RenderJobResponseDefaultTypeInternal _RenderJobResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RenderJobResponse_class_data_;
class RenderStatusRequest;
struct RenderStatusRequestDefaultTypeInternal;
extern RenderStatusRequestDefaultTypeInternal _RenderStatusRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RenderStatusRequest_class_data_;
class RenderStatusResponse;
struct RenderStatusResponseDefaultTypeInternal;
extern RenderStatusResponseDefaultTypeInternal _RenderStatusResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RenderStatusResponse_class_data_;
}  // namespace render_server
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::render_server::Status_internal_data_>
    internal::EnumTraitsImpl::value<::render_server::Status>;
}  // namespace protobuf
}  // namespace google

namespace render_server {
enum Status : int {
  PENDING = 0,
  RENDERING = 1,
  DONE = 2,
  Status_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Status_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Status_internal_data_[];
inline constexpr Status Status_MIN =
    static_cast<Status>(0);
inline constexpr Status Status_MAX =
    static_cast<Status>(2);
inline bool Status_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Status_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor();
template <typename T>
const ::std::string& Status_Name(T value) {
  static_assert(::std::is_same<T, Status>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Status_Name().");
  return Status_Name(static_cast<Status>(value));
}
template <>
inline const ::std::string& Status_Name(Status value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Status_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool Status_Parse(
    ::absl::string_view name, Status* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Status>(Status_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class RenderStatusResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:render_server.RenderStatusResponse) */ {
 public:
  inline RenderStatusResponse() : RenderStatusResponse(nullptr) {}
  ~RenderStatusResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RenderStatusResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RenderStatusResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RenderStatusResponse(::google::protobuf::internal::ConstantInitialized);

  inline RenderStatusResponse(const RenderStatusResponse& from) : RenderStatusResponse(nullptr, from) {}
  inline RenderStatusResponse(RenderStatusResponse&& from) noexcept
      : RenderStatusResponse(nullptr, ::std::move(from)) {}
  inline RenderStatusResponse& operator=(const RenderStatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RenderStatusResponse& operator=(RenderStatusResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RenderStatusResponse& default_instance() {
    return *reinterpret_cast<const RenderStatusResponse*>(
        &_RenderStatusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(RenderStatusResponse& a, RenderStatusResponse& b) { a.Swap(&b); }
  inline void Swap(RenderStatusResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RenderStatusResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RenderStatusResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RenderStatusResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RenderStatusResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RenderStatusResponse& from) { RenderStatusResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RenderStatusResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "render_server.RenderStatusResponse"; }

  explicit RenderStatusResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RenderStatusResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RenderStatusResponse& from);
  RenderStatusResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RenderStatusResponse&& from) noexcept
      : RenderStatusResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
  };
  // .render_server.Status status = 1;
  void clear_status() ;
  ::render_server::Status status() const;
  void set_status(::render_server::Status value);

  private:
  ::render_server::Status _internal_status() const;
  void _internal_set_status(::render_server::Status value);

  public:
  // @@protoc_insertion_point(class_scope:render_server.RenderStatusResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RenderStatusResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_render_5fserver_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RenderStatusResponse_class_data_;
// -------------------------------------------------------------------

class RenderStatusRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:render_server.RenderStatusRequest) */ {
 public:
  inline RenderStatusRequest() : RenderStatusRequest(nullptr) {}
  ~RenderStatusRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RenderStatusRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RenderStatusRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RenderStatusRequest(::google::protobuf::internal::ConstantInitialized);

  inline RenderStatusRequest(const RenderStatusRequest& from) : RenderStatusRequest(nullptr, from) {}
  inline RenderStatusRequest(RenderStatusRequest&& from) noexcept
      : RenderStatusRequest(nullptr, ::std::move(from)) {}
  inline RenderStatusRequest& operator=(const RenderStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RenderStatusRequest& operator=(RenderStatusRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RenderStatusRequest& default_instance() {
    return *reinterpret_cast<const RenderStatusRequest*>(
        &_RenderStatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(RenderStatusRequest& a, RenderStatusRequest& b) { a.Swap(&b); }
  inline void Swap(RenderStatusRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RenderStatusRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RenderStatusRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RenderStatusRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RenderStatusRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RenderStatusRequest& from) { RenderStatusRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RenderStatusRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "render_server.RenderStatusRequest"; }

  explicit RenderStatusRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RenderStatusRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RenderStatusRequest& from);
  RenderStatusRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RenderStatusRequest&& from) noexcept
      : RenderStatusRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kJobIdentifierFieldNumber = 1,
  };
  // int32 job_identifier = 1;
  void clear_job_identifier() ;
  ::int32_t job_identifier() const;
  void set_job_identifier(::int32_t value);

  private:
  ::int32_t _internal_job_identifier() const;
  void _internal_set_job_identifier(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:render_server.RenderStatusRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RenderStatusRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t job_identifier_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_render_5fserver_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RenderStatusRequest_class_data_;
// -------------------------------------------------------------------

class RenderJobResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:render_server.RenderJobResponse) */ {
 public:
  inline RenderJobResponse() : RenderJobResponse(nullptr) {}
  ~RenderJobResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RenderJobResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RenderJobResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RenderJobResponse(::google::protobuf::internal::ConstantInitialized);

  inline RenderJobResponse(const RenderJobResponse& from) : RenderJobResponse(nullptr, from) {}
  inline RenderJobResponse(RenderJobResponse&& from) noexcept
      : RenderJobResponse(nullptr, ::std::move(from)) {}
  inline RenderJobResponse& operator=(const RenderJobResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RenderJobResponse& operator=(RenderJobResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RenderJobResponse& default_instance() {
    return *reinterpret_cast<const RenderJobResponse*>(
        &_RenderJobResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RenderJobResponse& a, RenderJobResponse& b) { a.Swap(&b); }
  inline void Swap(RenderJobResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RenderJobResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RenderJobResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RenderJobResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RenderJobResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RenderJobResponse& from) { RenderJobResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RenderJobResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "render_server.RenderJobResponse"; }

  explicit RenderJobResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RenderJobResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RenderJobResponse& from);
  RenderJobResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RenderJobResponse&& from) noexcept
      : RenderJobResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kJobIdentifierFieldNumber = 1,
  };
  // int32 job_identifier = 1;
  void clear_job_identifier() ;
  ::int32_t job_identifier() const;
  void set_job_identifier(::int32_t value);

  private:
  ::int32_t _internal_job_identifier() const;
  void _internal_set_job_identifier(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:render_server.RenderJobResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RenderJobResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t job_identifier_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_render_5fserver_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RenderJobResponse_class_data_;
// -------------------------------------------------------------------

class RenderJobRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:render_server.RenderJobRequest) */ {
 public:
  inline RenderJobRequest() : RenderJobRequest(nullptr) {}
  ~RenderJobRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RenderJobRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RenderJobRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RenderJobRequest(::google::protobuf::internal::ConstantInitialized);

  inline RenderJobRequest(const RenderJobRequest& from) : RenderJobRequest(nullptr, from) {}
  inline RenderJobRequest(RenderJobRequest&& from) noexcept
      : RenderJobRequest(nullptr, ::std::move(from)) {}
  inline RenderJobRequest& operator=(const RenderJobRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RenderJobRequest& operator=(RenderJobRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RenderJobRequest& default_instance() {
    return *reinterpret_cast<const RenderJobRequest*>(
        &_RenderJobRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RenderJobRequest& a, RenderJobRequest& b) { a.Swap(&b); }
  inline void Swap(RenderJobRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RenderJobRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RenderJobRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RenderJobRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RenderJobRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RenderJobRequest& from) { RenderJobRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RenderJobRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "render_server.RenderJobRequest"; }

  explicit RenderJobRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RenderJobRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RenderJobRequest& from);
  RenderJobRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RenderJobRequest&& from) noexcept
      : RenderJobRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSceneLocationFieldNumber = 1,
    kSecondsFieldNumber = 2,
    kFramesFieldNumber = 3,
  };
  // string scene_location = 1;
  void clear_scene_location() ;
  const ::std::string& scene_location() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_scene_location(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_scene_location();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_scene_location();
  void set_allocated_scene_location(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_scene_location() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_scene_location(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_scene_location();

  public:
  // uint32 seconds = 2;
  void clear_seconds() ;
  ::uint32_t seconds() const;
  void set_seconds(::uint32_t value);

  private:
  ::uint32_t _internal_seconds() const;
  void _internal_set_seconds(::uint32_t value);

  public:
  // uint32 frames = 3;
  void clear_frames() ;
  ::uint32_t frames() const;
  void set_frames(::uint32_t value);

  private:
  ::uint32_t _internal_frames() const;
  void _internal_set_frames(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:render_server.RenderJobRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 53,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RenderJobRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr scene_location_;
    ::uint32_t seconds_;
    ::uint32_t frames_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_render_5fserver_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RenderJobRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RenderJobRequest

// string scene_location = 1;
inline void RenderJobRequest::clear_scene_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scene_location_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RenderJobRequest::scene_location() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:render_server.RenderJobRequest.scene_location)
  return _internal_scene_location();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RenderJobRequest::set_scene_location(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.scene_location_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:render_server.RenderJobRequest.scene_location)
}
inline ::std::string* PROTOBUF_NONNULL RenderJobRequest::mutable_scene_location()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_scene_location();
  // @@protoc_insertion_point(field_mutable:render_server.RenderJobRequest.scene_location)
  return _s;
}
inline const ::std::string& RenderJobRequest::_internal_scene_location() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scene_location_.Get();
}
inline void RenderJobRequest::_internal_set_scene_location(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scene_location_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RenderJobRequest::_internal_mutable_scene_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.scene_location_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RenderJobRequest::release_scene_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:render_server.RenderJobRequest.scene_location)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.scene_location_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.scene_location_.Set("", GetArena());
  }
  return released;
}
inline void RenderJobRequest::set_allocated_scene_location(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.scene_location_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.scene_location_.IsDefault()) {
    _impl_.scene_location_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:render_server.RenderJobRequest.scene_location)
}

// uint32 seconds = 2;
inline void RenderJobRequest::clear_seconds() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seconds_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t RenderJobRequest::seconds() const {
  // @@protoc_insertion_point(field_get:render_server.RenderJobRequest.seconds)
  return _internal_seconds();
}
inline void RenderJobRequest::set_seconds(::uint32_t value) {
  _internal_set_seconds(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:render_server.RenderJobRequest.seconds)
}
inline ::uint32_t RenderJobRequest::_internal_seconds() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.seconds_;
}
inline void RenderJobRequest::_internal_set_seconds(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seconds_ = value;
}

// uint32 frames = 3;
inline void RenderJobRequest::clear_frames() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.frames_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t RenderJobRequest::frames() const {
  // @@protoc_insertion_point(field_get:render_server.RenderJobRequest.frames)
  return _internal_frames();
}
inline void RenderJobRequest::set_frames(::uint32_t value) {
  _internal_set_frames(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:render_server.RenderJobRequest.frames)
}
inline ::uint32_t RenderJobRequest::_internal_frames() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.frames_;
}
inline void RenderJobRequest::_internal_set_frames(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.frames_ = value;
}

// -------------------------------------------------------------------

// RenderJobResponse

// int32 job_identifier = 1;
inline void RenderJobResponse::clear_job_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.job_identifier_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t RenderJobResponse::job_identifier() const {
  // @@protoc_insertion_point(field_get:render_server.RenderJobResponse.job_identifier)
  return _internal_job_identifier();
}
inline void RenderJobResponse::set_job_identifier(::int32_t value) {
  _internal_set_job_identifier(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:render_server.RenderJobResponse.job_identifier)
}
inline ::int32_t RenderJobResponse::_internal_job_identifier() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.job_identifier_;
}
inline void RenderJobResponse::_internal_set_job_identifier(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.job_identifier_ = value;
}

// -------------------------------------------------------------------

// RenderStatusRequest

// int32 job_identifier = 1;
inline void RenderStatusRequest::clear_job_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.job_identifier_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t RenderStatusRequest::job_identifier() const {
  // @@protoc_insertion_point(field_get:render_server.RenderStatusRequest.job_identifier)
  return _internal_job_identifier();
}
inline void RenderStatusRequest::set_job_identifier(::int32_t value) {
  _internal_set_job_identifier(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:render_server.RenderStatusRequest.job_identifier)
}
inline ::int32_t RenderStatusRequest::_internal_job_identifier() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.job_identifier_;
}
inline void RenderStatusRequest::_internal_set_job_identifier(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.job_identifier_ = value;
}

// -------------------------------------------------------------------

// RenderStatusResponse

// .render_server.Status status = 1;
inline void RenderStatusResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::render_server::Status RenderStatusResponse::status() const {
  // @@protoc_insertion_point(field_get:render_server.RenderStatusResponse.status)
  return _internal_status();
}
inline void RenderStatusResponse::set_status(::render_server::Status value) {
  _internal_set_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:render_server.RenderStatusResponse.status)
}
inline ::render_server::Status RenderStatusResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::render_server::Status>(_impl_.status_);
}
inline void RenderStatusResponse::_internal_set_status(::render_server::Status value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace render_server


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::render_server::Status> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::render_server::Status>() {
  return ::render_server::Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // render_5fserver_2eproto_2epb_2eh
