// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: render_server.proto
// Protobuf C++ Version: 6.33.4

#include "render_server.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace render_server {

inline constexpr RenderStatusResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        status_{static_cast< ::render_server::Status >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR RenderStatusResponse::RenderStatusResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RenderStatusResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RenderStatusResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RenderStatusResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RenderStatusResponseDefaultTypeInternal() {}
  union {
    RenderStatusResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RenderStatusResponseDefaultTypeInternal _RenderStatusResponse_default_instance_;

inline constexpr RenderStatusRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        job_identifier_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RenderStatusRequest::RenderStatusRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RenderStatusRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RenderStatusRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RenderStatusRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RenderStatusRequestDefaultTypeInternal() {}
  union {
    RenderStatusRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RenderStatusRequestDefaultTypeInternal _RenderStatusRequest_default_instance_;

inline constexpr RenderJobResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        job_identifier_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RenderJobResponse::RenderJobResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RenderJobResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RenderJobResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RenderJobResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RenderJobResponseDefaultTypeInternal() {}
  union {
    RenderJobResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RenderJobResponseDefaultTypeInternal _RenderJobResponse_default_instance_;

inline constexpr RenderJobRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        scene_location_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        seconds_{0u},
        frames_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR RenderJobRequest::RenderJobRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RenderJobRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RenderJobRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RenderJobRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RenderJobRequestDefaultTypeInternal() {}
  union {
    RenderJobRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RenderJobRequestDefaultTypeInternal _RenderJobRequest_default_instance_;
}  // namespace render_server
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_render_5fserver_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_render_5fserver_2eproto = nullptr;
const ::uint32_t
    TableStruct_render_5fserver_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::render_server::RenderJobRequest, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::render_server::RenderJobRequest, _impl_.scene_location_),
        PROTOBUF_FIELD_OFFSET(::render_server::RenderJobRequest, _impl_.seconds_),
        PROTOBUF_FIELD_OFFSET(::render_server::RenderJobRequest, _impl_.frames_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::render_server::RenderJobResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::render_server::RenderJobResponse, _impl_.job_identifier_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::render_server::RenderStatusRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::render_server::RenderStatusRequest, _impl_.job_identifier_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::render_server::RenderStatusResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::render_server::RenderStatusResponse, _impl_.status_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::render_server::RenderJobRequest)},
        {9, sizeof(::render_server::RenderJobResponse)},
        {14, sizeof(::render_server::RenderStatusRequest)},
        {19, sizeof(::render_server::RenderStatusResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::render_server::_RenderJobRequest_default_instance_._instance,
    &::render_server::_RenderJobResponse_default_instance_._instance,
    &::render_server::_RenderStatusRequest_default_instance_._instance,
    &::render_server::_RenderStatusResponse_default_instance_._instance,
};
const char descriptor_table_protodef_render_5fserver_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023render_server.proto\022\rrender_server\"K\n\020"
    "RenderJobRequest\022\026\n\016scene_location\030\001 \001(\t"
    "\022\017\n\007seconds\030\002 \001(\r\022\016\n\006frames\030\003 \001(\r\"+\n\021Ren"
    "derJobResponse\022\026\n\016job_identifier\030\001 \001(\005\"-"
    "\n\023RenderStatusRequest\022\026\n\016job_identifier\030"
    "\001 \001(\005\"=\n\024RenderStatusResponse\022%\n\006status\030"
    "\001 \001(\0162\025.render_server.Status*.\n\006Status\022\013"
    "\n\007PENDING\020\000\022\r\n\tRENDERING\020\001\022\010\n\004DONE\020\0022\273\001\n"
    "\014RenderWorker\022P\n\tRenderJob\022\037.render_serv"
    "er.RenderJobRequest\032 .render_server.Rend"
    "erJobResponse\"\000\022Y\n\014RenderStatus\022\".render"
    "_server.RenderStatusRequest\032#.render_ser"
    "ver.RenderStatusResponse\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_render_5fserver_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_render_5fserver_2eproto = {
    false,
    false,
    514,
    descriptor_table_protodef_render_5fserver_2eproto,
    "render_server.proto",
    &descriptor_table_render_5fserver_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_render_5fserver_2eproto::offsets,
    file_level_enum_descriptors_render_5fserver_2eproto,
    file_level_service_descriptors_render_5fserver_2eproto,
};
namespace render_server {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_render_5fserver_2eproto);
  return file_level_enum_descriptors_render_5fserver_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Status_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class RenderJobRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RenderJobRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RenderJobRequest, _impl_._has_bits_);
};

RenderJobRequest::RenderJobRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RenderJobRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:render_server.RenderJobRequest)
}
PROTOBUF_NDEBUG_INLINE RenderJobRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::render_server::RenderJobRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        scene_location_(arena, from.scene_location_) {}

RenderJobRequest::RenderJobRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RenderJobRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RenderJobRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RenderJobRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, seconds_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, seconds_),
           offsetof(Impl_, frames_) -
               offsetof(Impl_, seconds_) +
               sizeof(Impl_::frames_));

  // @@protoc_insertion_point(copy_constructor:render_server.RenderJobRequest)
}
PROTOBUF_NDEBUG_INLINE RenderJobRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        scene_location_(arena) {}

inline void RenderJobRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, seconds_),
           0,
           offsetof(Impl_, frames_) -
               offsetof(Impl_, seconds_) +
               sizeof(Impl_::frames_));
}
RenderJobRequest::~RenderJobRequest() {
  // @@protoc_insertion_point(destructor:render_server.RenderJobRequest)
  SharedDtor(*this);
}
inline void RenderJobRequest::SharedDtor(MessageLite& self) {
  RenderJobRequest& this_ = static_cast<RenderJobRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.scene_location_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RenderJobRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RenderJobRequest(arena);
}
constexpr auto RenderJobRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RenderJobRequest),
                                            alignof(RenderJobRequest));
}
constexpr auto RenderJobRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RenderJobRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RenderJobRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RenderJobRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RenderJobRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RenderJobRequest>(), &RenderJobRequest::ByteSizeLong,
              &RenderJobRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RenderJobRequest, _impl_._cached_size_),
          false,
      },
      &RenderJobRequest::kDescriptorMethods,
      &descriptor_table_render_5fserver_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RenderJobRequest_class_data_ =
        RenderJobRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RenderJobRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RenderJobRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RenderJobRequest_class_data_.tc_table);
  return RenderJobRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 53, 2>
RenderJobRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RenderJobRequest, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RenderJobRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::render_server::RenderJobRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string scene_location = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RenderJobRequest, _impl_.scene_location_)}},
    // uint32 seconds = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RenderJobRequest, _impl_.seconds_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(RenderJobRequest, _impl_.seconds_)}},
    // uint32 frames = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RenderJobRequest, _impl_.frames_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(RenderJobRequest, _impl_.frames_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string scene_location = 1;
    {PROTOBUF_FIELD_OFFSET(RenderJobRequest, _impl_.scene_location_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 seconds = 2;
    {PROTOBUF_FIELD_OFFSET(RenderJobRequest, _impl_.seconds_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 frames = 3;
    {PROTOBUF_FIELD_OFFSET(RenderJobRequest, _impl_.frames_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\36\16\0\0\0\0\0\0"
    "render_server.RenderJobRequest"
    "scene_location"
  }},
};
PROTOBUF_NOINLINE void RenderJobRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:render_server.RenderJobRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.scene_location_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.seconds_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.frames_) -
        reinterpret_cast<char*>(&_impl_.seconds_)) + sizeof(_impl_.frames_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RenderJobRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RenderJobRequest& this_ = static_cast<const RenderJobRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RenderJobRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RenderJobRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:render_server.RenderJobRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string scene_location = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_scene_location().empty()) {
      const ::std::string& _s = this_._internal_scene_location();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "render_server.RenderJobRequest.scene_location");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // uint32 seconds = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_seconds() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_seconds(), target);
    }
  }

  // uint32 frames = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_frames() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_frames(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:render_server.RenderJobRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RenderJobRequest::ByteSizeLong(const MessageLite& base) {
  const RenderJobRequest& this_ = static_cast<const RenderJobRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RenderJobRequest::ByteSizeLong() const {
  const RenderJobRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:render_server.RenderJobRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string scene_location = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_scene_location().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_scene_location());
      }
    }
    // uint32 seconds = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_seconds() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_seconds());
      }
    }
    // uint32 frames = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_frames() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_frames());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RenderJobRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RenderJobRequest*>(&to_msg);
  auto& from = static_cast<const RenderJobRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:render_server.RenderJobRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_scene_location().empty()) {
        _this->_internal_set_scene_location(from._internal_scene_location());
      } else {
        if (_this->_impl_.scene_location_.IsDefault()) {
          _this->_internal_set_scene_location("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_seconds() != 0) {
        _this->_impl_.seconds_ = from._impl_.seconds_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_frames() != 0) {
        _this->_impl_.frames_ = from._impl_.frames_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RenderJobRequest::CopyFrom(const RenderJobRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:render_server.RenderJobRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RenderJobRequest::InternalSwap(RenderJobRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.scene_location_, &other->_impl_.scene_location_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RenderJobRequest, _impl_.frames_)
      + sizeof(RenderJobRequest::_impl_.frames_)
      - PROTOBUF_FIELD_OFFSET(RenderJobRequest, _impl_.seconds_)>(
          reinterpret_cast<char*>(&_impl_.seconds_),
          reinterpret_cast<char*>(&other->_impl_.seconds_));
}

::google::protobuf::Metadata RenderJobRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RenderJobResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RenderJobResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RenderJobResponse, _impl_._has_bits_);
};

RenderJobResponse::RenderJobResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RenderJobResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:render_server.RenderJobResponse)
}
RenderJobResponse::RenderJobResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RenderJobResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RenderJobResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE RenderJobResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void RenderJobResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.job_identifier_ = {};
}
RenderJobResponse::~RenderJobResponse() {
  // @@protoc_insertion_point(destructor:render_server.RenderJobResponse)
  SharedDtor(*this);
}
inline void RenderJobResponse::SharedDtor(MessageLite& self) {
  RenderJobResponse& this_ = static_cast<RenderJobResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RenderJobResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RenderJobResponse(arena);
}
constexpr auto RenderJobResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RenderJobResponse),
                                            alignof(RenderJobResponse));
}
constexpr auto RenderJobResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RenderJobResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RenderJobResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RenderJobResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RenderJobResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RenderJobResponse>(), &RenderJobResponse::ByteSizeLong,
              &RenderJobResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RenderJobResponse, _impl_._cached_size_),
          false,
      },
      &RenderJobResponse::kDescriptorMethods,
      &descriptor_table_render_5fserver_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RenderJobResponse_class_data_ =
        RenderJobResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RenderJobResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RenderJobResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RenderJobResponse_class_data_.tc_table);
  return RenderJobResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
RenderJobResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RenderJobResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RenderJobResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::render_server::RenderJobResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 job_identifier = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RenderJobResponse, _impl_.job_identifier_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(RenderJobResponse, _impl_.job_identifier_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 job_identifier = 1;
    {PROTOBUF_FIELD_OFFSET(RenderJobResponse, _impl_.job_identifier_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void RenderJobResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:render_server.RenderJobResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.job_identifier_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RenderJobResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RenderJobResponse& this_ = static_cast<const RenderJobResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RenderJobResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RenderJobResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:render_server.RenderJobResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 job_identifier = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_job_identifier() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_job_identifier(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:render_server.RenderJobResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RenderJobResponse::ByteSizeLong(const MessageLite& base) {
  const RenderJobResponse& this_ = static_cast<const RenderJobResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RenderJobResponse::ByteSizeLong() const {
  const RenderJobResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:render_server.RenderJobResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 job_identifier = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_job_identifier() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_job_identifier());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RenderJobResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RenderJobResponse*>(&to_msg);
  auto& from = static_cast<const RenderJobResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:render_server.RenderJobResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_job_identifier() != 0) {
      _this->_impl_.job_identifier_ = from._impl_.job_identifier_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RenderJobResponse::CopyFrom(const RenderJobResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:render_server.RenderJobResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RenderJobResponse::InternalSwap(RenderJobResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.job_identifier_, other->_impl_.job_identifier_);
}

::google::protobuf::Metadata RenderJobResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RenderStatusRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RenderStatusRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RenderStatusRequest, _impl_._has_bits_);
};

RenderStatusRequest::RenderStatusRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RenderStatusRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:render_server.RenderStatusRequest)
}
RenderStatusRequest::RenderStatusRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RenderStatusRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RenderStatusRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE RenderStatusRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void RenderStatusRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.job_identifier_ = {};
}
RenderStatusRequest::~RenderStatusRequest() {
  // @@protoc_insertion_point(destructor:render_server.RenderStatusRequest)
  SharedDtor(*this);
}
inline void RenderStatusRequest::SharedDtor(MessageLite& self) {
  RenderStatusRequest& this_ = static_cast<RenderStatusRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RenderStatusRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RenderStatusRequest(arena);
}
constexpr auto RenderStatusRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RenderStatusRequest),
                                            alignof(RenderStatusRequest));
}
constexpr auto RenderStatusRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RenderStatusRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RenderStatusRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RenderStatusRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RenderStatusRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RenderStatusRequest>(), &RenderStatusRequest::ByteSizeLong,
              &RenderStatusRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RenderStatusRequest, _impl_._cached_size_),
          false,
      },
      &RenderStatusRequest::kDescriptorMethods,
      &descriptor_table_render_5fserver_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RenderStatusRequest_class_data_ =
        RenderStatusRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RenderStatusRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RenderStatusRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RenderStatusRequest_class_data_.tc_table);
  return RenderStatusRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
RenderStatusRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RenderStatusRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RenderStatusRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::render_server::RenderStatusRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 job_identifier = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RenderStatusRequest, _impl_.job_identifier_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(RenderStatusRequest, _impl_.job_identifier_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 job_identifier = 1;
    {PROTOBUF_FIELD_OFFSET(RenderStatusRequest, _impl_.job_identifier_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void RenderStatusRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:render_server.RenderStatusRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.job_identifier_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RenderStatusRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RenderStatusRequest& this_ = static_cast<const RenderStatusRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RenderStatusRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RenderStatusRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:render_server.RenderStatusRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 job_identifier = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_job_identifier() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_job_identifier(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:render_server.RenderStatusRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RenderStatusRequest::ByteSizeLong(const MessageLite& base) {
  const RenderStatusRequest& this_ = static_cast<const RenderStatusRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RenderStatusRequest::ByteSizeLong() const {
  const RenderStatusRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:render_server.RenderStatusRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 job_identifier = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_job_identifier() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_job_identifier());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RenderStatusRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RenderStatusRequest*>(&to_msg);
  auto& from = static_cast<const RenderStatusRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:render_server.RenderStatusRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_job_identifier() != 0) {
      _this->_impl_.job_identifier_ = from._impl_.job_identifier_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RenderStatusRequest::CopyFrom(const RenderStatusRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:render_server.RenderStatusRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RenderStatusRequest::InternalSwap(RenderStatusRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.job_identifier_, other->_impl_.job_identifier_);
}

::google::protobuf::Metadata RenderStatusRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RenderStatusResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RenderStatusResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RenderStatusResponse, _impl_._has_bits_);
};

RenderStatusResponse::RenderStatusResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RenderStatusResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:render_server.RenderStatusResponse)
}
RenderStatusResponse::RenderStatusResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RenderStatusResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RenderStatusResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE RenderStatusResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void RenderStatusResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
RenderStatusResponse::~RenderStatusResponse() {
  // @@protoc_insertion_point(destructor:render_server.RenderStatusResponse)
  SharedDtor(*this);
}
inline void RenderStatusResponse::SharedDtor(MessageLite& self) {
  RenderStatusResponse& this_ = static_cast<RenderStatusResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RenderStatusResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RenderStatusResponse(arena);
}
constexpr auto RenderStatusResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RenderStatusResponse),
                                            alignof(RenderStatusResponse));
}
constexpr auto RenderStatusResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RenderStatusResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RenderStatusResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RenderStatusResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RenderStatusResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RenderStatusResponse>(), &RenderStatusResponse::ByteSizeLong,
              &RenderStatusResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RenderStatusResponse, _impl_._cached_size_),
          false,
      },
      &RenderStatusResponse::kDescriptorMethods,
      &descriptor_table_render_5fserver_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RenderStatusResponse_class_data_ =
        RenderStatusResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RenderStatusResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RenderStatusResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RenderStatusResponse_class_data_.tc_table);
  return RenderStatusResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
RenderStatusResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RenderStatusResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RenderStatusResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::render_server::RenderStatusResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .render_server.Status status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RenderStatusResponse, _impl_.status_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(RenderStatusResponse, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .render_server.Status status = 1;
    {PROTOBUF_FIELD_OFFSET(RenderStatusResponse, _impl_.status_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void RenderStatusResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:render_server.RenderStatusResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RenderStatusResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RenderStatusResponse& this_ = static_cast<const RenderStatusResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RenderStatusResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RenderStatusResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:render_server.RenderStatusResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .render_server.Status status = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_status(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:render_server.RenderStatusResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RenderStatusResponse::ByteSizeLong(const MessageLite& base) {
  const RenderStatusResponse& this_ = static_cast<const RenderStatusResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RenderStatusResponse::ByteSizeLong() const {
  const RenderStatusResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:render_server.RenderStatusResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .render_server.Status status = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RenderStatusResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RenderStatusResponse*>(&to_msg);
  auto& from = static_cast<const RenderStatusResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:render_server.RenderStatusResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_status() != 0) {
      _this->_impl_.status_ = from._impl_.status_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RenderStatusResponse::CopyFrom(const RenderStatusResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:render_server.RenderStatusResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RenderStatusResponse::InternalSwap(RenderStatusResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata RenderStatusResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace render_server
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_render_5fserver_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
