// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scheduler_server.proto
// Protobuf C++ Version: 6.33.4

#ifndef scheduler_5fserver_2eproto_2epb_2eh
#define scheduler_5fserver_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/empty.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_scheduler_5fserver_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_scheduler_5fserver_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_scheduler_5fserver_2eproto;
}  // extern "C"
namespace scheduler_server {
class WorkerConncetion;
struct WorkerConncetionDefaultTypeInternal;
extern WorkerConncetionDefaultTypeInternal _WorkerConncetion_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WorkerConncetion_class_data_;
}  // namespace scheduler_server
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace scheduler_server {

// ===================================================================


// -------------------------------------------------------------------

class WorkerConncetion final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:scheduler_server.WorkerConncetion) */ {
 public:
  inline WorkerConncetion() : WorkerConncetion(nullptr) {}
  ~WorkerConncetion() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WorkerConncetion* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WorkerConncetion));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WorkerConncetion(::google::protobuf::internal::ConstantInitialized);

  inline WorkerConncetion(const WorkerConncetion& from) : WorkerConncetion(nullptr, from) {}
  inline WorkerConncetion(WorkerConncetion&& from) noexcept
      : WorkerConncetion(nullptr, ::std::move(from)) {}
  inline WorkerConncetion& operator=(const WorkerConncetion& from) {
    CopyFrom(from);
    return *this;
  }
  inline WorkerConncetion& operator=(WorkerConncetion&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WorkerConncetion& default_instance() {
    return *reinterpret_cast<const WorkerConncetion*>(
        &_WorkerConncetion_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(WorkerConncetion& a, WorkerConncetion& b) { a.Swap(&b); }
  inline void Swap(WorkerConncetion* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WorkerConncetion* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WorkerConncetion* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WorkerConncetion>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WorkerConncetion& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WorkerConncetion& from) { WorkerConncetion::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WorkerConncetion* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "scheduler_server.WorkerConncetion"; }

  explicit WorkerConncetion(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WorkerConncetion(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WorkerConncetion& from);
  WorkerConncetion(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WorkerConncetion&& from) noexcept
      : WorkerConncetion(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWorkerIpFieldNumber = 1,
  };
  // string worker_ip = 1;
  void clear_worker_ip() ;
  const ::std::string& worker_ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_worker_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_worker_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_worker_ip();
  void set_allocated_worker_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_worker_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_worker_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_worker_ip();

  public:
  // @@protoc_insertion_point(class_scope:scheduler_server.WorkerConncetion)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 51,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WorkerConncetion& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr worker_ip_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scheduler_5fserver_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WorkerConncetion_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// WorkerConncetion

// string worker_ip = 1;
inline void WorkerConncetion::clear_worker_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.worker_ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& WorkerConncetion::worker_ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:scheduler_server.WorkerConncetion.worker_ip)
  return _internal_worker_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void WorkerConncetion::set_worker_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.worker_ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:scheduler_server.WorkerConncetion.worker_ip)
}
inline ::std::string* PROTOBUF_NONNULL WorkerConncetion::mutable_worker_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_worker_ip();
  // @@protoc_insertion_point(field_mutable:scheduler_server.WorkerConncetion.worker_ip)
  return _s;
}
inline const ::std::string& WorkerConncetion::_internal_worker_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.worker_ip_.Get();
}
inline void WorkerConncetion::_internal_set_worker_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.worker_ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL WorkerConncetion::_internal_mutable_worker_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.worker_ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE WorkerConncetion::release_worker_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:scheduler_server.WorkerConncetion.worker_ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.worker_ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.worker_ip_.Set("", GetArena());
  }
  return released;
}
inline void WorkerConncetion::set_allocated_worker_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.worker_ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.worker_ip_.IsDefault()) {
    _impl_.worker_ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:scheduler_server.WorkerConncetion.worker_ip)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace scheduler_server


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // scheduler_5fserver_2eproto_2epb_2eh
